version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: book-store
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    

  book-store:
    build: .
    container_name: book-store-container
    ports:
      - "3000:3000"
    depends_on: 
      - postgres

  # nginx:
  #   container_name: nginx-contaniner
  #   image: nginx
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - book-store
   

volumes:
  postgres-data:
