# TODO
# Change the secrets and naming 

version: '3'

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2

  book-store-microservice:
    build: ./path/to/your/go-microservice
    ports:
      - "8080:8080"  # Assuming your microservice exposes port 8080
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3

volumes:
  postgres_data:
