// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package database

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Author      string         `json:"author"`
	Genre       string         `json:"genre"`
	Price       pgtype.Numeric `json:"price"`
	Description pgtype.Text    `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Cart struct {
	ID        int64     `json:"id"`
	UserID    int32     `json:"user_id"`
	BookID    int32     `json:"book_id"`
	Quantity  int32     `json:"quantity"`
	CreatedAt time.Time `json:"created_at"`
}

type Purchase struct {
	ID        int64     `json:"id"`
	UserID    int32     `json:"user_id"`
	BookID    int32     `json:"book_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Review struct {
	ID        int64       `json:"id"`
	UserID    int32       `json:"user_id"`
	BookID    int32       `json:"book_id"`
	Rating    int32       `json:"rating"`
	Comment   pgtype.Text `json:"comment"`
	CreatedAt time.Time   `json:"created_at"`
}

type User struct {
	ID        int64       `json:"id"`
	Username  string      `json:"username"`
	Password  string      `json:"password"`
	IsAdmin   pgtype.Bool `json:"is_admin"`
	CreatedAt time.Time   `json:"created_at"`
}
