// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: order.sql

package database

import (
	"context"
)

const addOrder = `-- name: AddOrder :one
INSERT INTO "Orders" (
  razorpay_order_id, user_id, total_money, status
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, razorpay_order_id, user_id, total_money, status, created_at
`

type AddOrderParams struct {
	RazorpayOrderID string  `json:"razorpay_order_id"`
	UserID          int64   `json:"user_id"`
	TotalMoney      float64 `json:"total_money"`
	Status          string  `json:"status"`
}

func (q *Queries) AddOrder(ctx context.Context, arg AddOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, addOrder,
		arg.RazorpayOrderID,
		arg.UserID,
		arg.TotalMoney,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.RazorpayOrderID,
		&i.UserID,
		&i.TotalMoney,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrdersOfUser = `-- name: DeleteOrdersOfUser :exec
delete from "Orders"
where user_id = $1
`

func (q *Queries) DeleteOrdersOfUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteOrdersOfUser, userID)
	return err
}

const getOrderById = `-- name: GetOrderById :one
select id, razorpay_order_id, user_id, total_money, status, created_at from "Orders"
where id = $1 and user_id = $2
`

type GetOrderByIdParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetOrderById(ctx context.Context, arg GetOrderByIdParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderById, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.RazorpayOrderID,
		&i.UserID,
		&i.TotalMoney,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE "Orders"
set "status" = $1
WHERE "id" = $2 and user_id = $3
RETURNING id, razorpay_order_id, user_id, total_money, status, created_at
`

type UpdateOrderParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder, arg.Status, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.RazorpayOrderID,
		&i.UserID,
		&i.TotalMoney,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
