// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateTag(ctx context.Context, tagName string) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBook(ctx context.Context, id int64) error
	DeleteReview(ctx context.Context, id int64) error
	GetAllTags(ctx context.Context) ([]Tag, error)
	GetBook(ctx context.Context, id int64) (Book, error)
	GetBooks(ctx context.Context, arg GetBooksParams) ([]Book, error)
	GetReviewsByBookId(ctx context.Context, arg GetReviewsByBookIdParams) ([]Review, error)
	GetTagsByBookId(ctx context.Context, id int64) ([]string, error)
	GetUser(ctx context.Context, id int64) (User, error)
	UpdateBookDesc(ctx context.Context, arg UpdateBookDescParams) (Book, error)
	UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error)
}

var _ Querier = (*Queries)(nil)
