// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddOrder(ctx context.Context, arg AddOrderParams) (Order, error)
	AddToCart(ctx context.Context, arg AddToCartParams) (Cart, error)
	CheckAdmin(ctx context.Context, id int64) (User, error)
	CheckBookPurchased(ctx context.Context, arg CheckBookPurchasedParams) (Purchase, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	DeleteBook(ctx context.Context, id int64) error
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error
	DeleteOrder(ctx context.Context, userID int64) error
	DeletePurchase(ctx context.Context, userID int64) error
	DeleteReview(ctx context.Context, id int64) error
	DeleteSession(ctx context.Context, userID int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteVerifyEmail(ctx context.Context, userID int64) error
	GetAllTags(ctx context.Context) ([]Tag, error)
	GetBookById(ctx context.Context, id int64) (GetBookByIdRow, error)
	GetCartItemsByUserId(ctx context.Context, userID int64) ([]GetCartItemsByUserIdRow, error)
	GetHotSellingBooks(ctx context.Context, arg GetHotSellingBooksParams) ([]GetHotSellingBooksRow, error)
	GetOrderById(ctx context.Context, arg GetOrderByIdParams) (Order, error)
	// todo this is to get bought books at a single place
	GetPurchasedBooks(ctx context.Context, arg GetPurchasedBooksParams) ([]GetPurchasedBooksRow, error)
	GetReviewsByBookId(ctx context.Context, arg GetReviewsByBookIdParams) ([]Review, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetTotalCartAmountById(ctx context.Context, userID int64) (int64, error)
	GetUser(ctx context.Context, arg GetUserParams) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserRecommendations(ctx context.Context, arg GetUserRecommendationsParams) ([]GetUserRecommendationsRow, error)
	// TODO fuzzy searching add karni hain isme fkin
	SearchBooksV1(ctx context.Context, arg SearchBooksV1Params) ([]SearchBooksV1Row, error)
	SearchBooksV2(ctx context.Context, arg SearchBooksV2Params) ([]SearchBooksV2Row, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	// todo test this timeout feature how is this working
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
