// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: query.sql

package database

import (
	"context"
)

const getAllBooks = `-- name: GetAllBooks :one
select id, title, author, genre, price, description, created_at from "Books"
where id = $1 LIMIT 1
`

func (q *Queries) GetAllBooks(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRow(ctx, getAllBooks, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Genre,
		&i.Price,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
